apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.backend.name }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.backend.DATABASE_URL | quote }}
  JWT_SECRET: {{ .Values.secrets.backend.JWT_SECRET | quote }}